### ISSUE TITLE
d3-scale-chromatic 404'ing

### ISSUE THREAD

**Issue by ianrose** [BastiTee/d3-workbench#12]
In demo and new project getting a 404 for `../../libs/d3-scale-chromatic/build/d3-scale-chromatic.min.js`

Looking at the`d3-scale-chromatic` package, the output is in a `dist` rather than `build`

**Comment by BastiTee** [comment]
Hey Ian, thanks a lot for your feedback. 

This only happens when running `npm install`, not on `yarn install`.
I removed yarn and adopted the basic `npm` workflow.
On HEAD this will be fixed with the next commit.

**Comment by BastiTee** [comment]
The new 0.9.2 patch release available on NPM includes this fix: <https://www.npmjs.com/package/d3-workbench>
