### ISSUE TITLE
blog/tutorial down

### ISSUE THREAD

**Issue by shaunc** [BastiTee/d3-workbench#13]
Looks like an interesting project. The blog is down. Also, there seems to be a pause in development. Is this still under active development, or has it been abandoned?

**Comment by BastiTee** [comment]
Hey @shaunc 

I would love to tell differently, but as of now I haven't found any collaborators on this plus a head full of work-related coding. So the answer is yes unfortunately. This project is for now abandoned / not under active development. 

But thanks for the hint. I will make sure that the blog links will be active again soon. I will let you know.

**Comment by BastiTee** [comment]
Hey @shaunc the blog is back up. So is the tutorial: https://bastis.cloud/2018/03/05/d3wb-chart-tutorial.html
