### ISSUE TITLE
Starting d3-workbench with a firefox process already running will cause a fatal error

### ISSUE THREAD

**Issue by Rebstorm** [BastiTee/d3-workbench#2]
Hello.

Trying to run node d3-wb-server.js -i /path/to/workbench/ will not work if Firefox is already running, I guess it has something to do with you trying to start the process and if its already started it wont work? 
![screenshot_20171109_155055](https://user-images.githubusercontent.com/15019822/32613007-01166e02-c56a-11e7-8a0e-bd52245e60c8.png)

**Comment by BastiTee** [comment]
Hmm, I never ran into this issue and never took care whether the browser is open or closed. Are you sure this wasn't a temporary issue and all firefox processes were frozen?

**Comment by Rebstorm** [comment]
Possibly. It seems to be working fine today with npm start. Sounds more node related IMHO than d3-workbench.

**Comment by BastiTee** [comment]
I'll close it for now, but just let me know, if you discover it again. Maybe we can debug then. Thanks
